'use client';
import React from 'react';
import { useApp } from '@/context/AppContext';
import { useIsRTL } from '@/hooks/use-is-rtl';

export default function AcknowledgementsSection() {
  const { t } = useApp();
  const isRTL = useIsRTL();

  // Markdown-style list with links and attributions
  const acknowledgementsMarkdown = `
[La casettina del coniglio](https://www.archive.org/download/avventuredalice_1907_librivox/alicenelpaesemeraviglie_04_carroll_128kb.mp3) from [Le Avventure d'Alice nel Paese delle Meraviglie](https://librivox.org/le-avventure-dalice-nel-paese-delle-meraviglie-by-lewis-carroll/)

[La Camera in Attesa](https://www.archive.org/download/novelle_per_un_anno_vol_13_candelora_1503_librivox/novelle_per_un_anno_vol_13_candelora_03_pirandello_128kb.mp3) from [Novelle per un Anno, vol. 13: Candelora](https://librivox.org/novelle-per-un-anno-vol-13-candelora-by-luigi-pirandello/)

[Esser morta vorrei...](https://www.archive.org/download/multilingual_poetry_collection_004_librivox/italian_essermortavorrei_saffo_aa.mp3) from [Multilingual Poetry Collection 004](https://librivox.org/multilingual-poetry-collection-004/)

[Il croquet della regina](https://www.archive.org/download/avventuredalice_1907_librivox/alicenelpaesemeraviglie_08_carroll_128kb.mp3) from [Le Avventure d'Alice nel Paese delle Meraviglie](https://librivox.org/le-avventure-dalice-nel-paese-delle-meraviglie-by-lewis-carroll/)

[Image](https://grok.com/imagine/post/b79789ab-b9e1-4fa5-9e11-9f82bdb2fc84?source=post-page&platform=web) generated by [Grok Imagine](https://www.grok.com/imagine)

[Success 03](https://freesound.org/s/322930/) by [rhodesmas](https://freesound.org/people/rhodesmas/) -- License: [Attribution 4.0](https://creativecommons.org/licenses/by/4.0/)

[Failure 01](https://freesound.org/s/342756/) by [rhodesmas](https://freesound.org/people/rhodesmas/) -- License: [Attribution 4.0](https://creativecommons.org/licenses/by/4.0/)

[Fanfare 2 - Rpg](https://freesound.org/s/580310/) by [colorsCrimsonTears](https://freesound.org/people/colorsCrimsonTears/) -- License: [Creative Commons 0](http://creativecommons.org/publicdomain/zero/1.0/)

[Chronicle Button](https://codepen.io/Haaguitos/pen/OJrVZdJ) by [Haaguitos](https://codepen.io/Haaguitos)

[Button hover effect](https://codepen.io/thebabydino/pen/PoxVZWg) by [Ana Tudor](https://codepen.io/thebabydino)

[Electric Border](https://codepen.io/BalintFerenczy/pen/KwdoyEN) by [Bálint Ferenczy](https://codepen.io/BalintFerenczy)

[Electric Border (iOS Safe)](https://codepen.io/BalintFerenczy/pen/yyYErXa) by [Bálint Ferenczy](https://codepen.io/BalintFerenczy)

[Toggle Vault](https://www.scrollxui.dev/docs/components/toggle-vault) by [ScrollX UI](https://www.scrollxui.dev/)

[Glowing Effect](https://ui.aceternity.com/components/glowing-effect) by [Aceternity UI](https://ui.aceternity.com/)

[すりガラスなプロフィールカード](https://codepen.io/ash_creator/pen/zYaPZLB) by [あしざわ - Webクリエイター](https://codepen.io/ash_creator)

[Glass Cards](https://codepen.io/RAFA3L/pen/NPKeYMo) by [Rafa](https://codepen.io/RAFA3L)

[Design Wormhole](https://codepen.io/RAFA3L/pen/WbedLaw) by [Rafa](https://codepen.io/RAFA3L)

[Accent Shard (On Hover)](https://codepen.io/Hyperplexed/pen/qBMYVoq) by [Hyperplexed](https://codepen.io/Hyperplexed)

[Custom Checkbox](https://21st.dev/Edil-ozi/custom-checkbox/default) by [Edil Ozi](https://21st.dev/Edil-ozi)

[チェックしないと押せないボタン](https://codepen.io/ash_creator/pen/JjZReNm) by [あしざわ - Webクリエイター](https://codepen.io/ash_creator)

[radix-ui](https://www.npmjs.com/package/radix-ui)

[Pagination](https://codepen.io/-we-code-/pen/oNRGgYQ) by [we-code](https://codepen.io/-we-code-)

[Pagination - with Sliding Animation](https://codepen.io/-we-code-/pen/ZENXgLe) by [we-code](https://codepen.io/-we-code-)

[Unnamed Luminous Material](https://x.com/gibkun1/status/2013734035454042547) by [タツキ｜サムネ顧問](https://x.com/gibkun1)

[framer-motion](https://www.npmjs.com/package/framer-motion)

[Lucide React](https://www.npmjs.com/package/lucide-react)

[Next.js](https://nextjs.org/)

[Perplexity](https://www.perplexity.ai/)

[Firebase Studio](https://firebase.studio/)

[Google AI Studio](https://aistudio.google.com/)
`;

  // Function to parse markdown [label](url) syntax
  function renderEntry(entry: string) {
    const regex = /\[([^\]]+)\]\(([^)]+)\)/g;
    const parts: React.ReactNode[] = [];
    let lastIndex = 0;
    let match: RegExpExecArray | null;
    let key = 0;

    while ((match = regex.exec(entry)) !== null) {
      // Text before the match
      if (match.index > lastIndex) {
        parts.push(
          <span key={key++} className="text-[hsl(var(--muted-foreground))]">
            {entry.slice(lastIndex, match.index)}
          </span>
        );
      }

      // The hyperlink (forced to LTR)
      parts.push(
        <a
          key={key++}
          href={match[2]}
          target="_blank"
          rel="noopener noreferrer"
          className="text-[hsl(var(--foreground)/0.9)] hover:text-[hsl(var(--primary))] hover:underline transition-colors"
          style={{ direction: 'ltr' }}
        >
          {match[1]}
        </a>
      );
      lastIndex = regex.lastIndex;
    }

    // Remaining text after final match
    if (lastIndex < entry.length) {
      parts.push(
        <span key={key++} className="text-[hsl(var(--muted-foreground))]">
          {entry.slice(lastIndex)}
        </span>
      );
    }

    return parts;
  }

  const entries = acknowledgementsMarkdown
    .trim()
    .split('\n')
    .map((line) => line.trim())
    .filter(Boolean);

  return (
    <section
      id="acknowledgements-section"
      className="w-full py-16 md:py-24 bg-background transition"
      dir={isRTL ? 'rtl' : 'ltr'}
    >
      <div className="max-w-[1296px] mx-auto px-6 md:px-10 w-full flex flex-col items-center justify-center text-center">
        <div className="mb-12">
          <h2 className="font-headline text-4xl md:text-5xl font-bold text-[hsl(var(--foreground))]">
            {t('acknowledgements')}
          </h2>
          <p className="text-muted-foreground mt-4 max-w-2xl mx-auto">
            {t('acknowledgementDescription')}
          </p>
        </div>

        <div
          className="max-w-3xl w-full flex flex-col items-center justify-center"
          style={{
            textAlign: 'center',
            direction: isRTL ? 'rtl' : 'ltr',
          }}
        >
          <ul
            className="w-full flex flex-col items-center justify-center"
            style={{
              listStyleType: 'none',
              padding: 0,
              margin: 0,
              lineHeight: 1.75,
            }}
          >
            {entries.map((entry, idx) => (
              <li
                key={idx}
                className="mb-4 last:mb-0 text-[1rem] text-[hsl(var(--muted-foreground))]"
                style={{
                  direction: 'ltr',
                  textAlign: 'center',
                  color: 'hsl(var(--muted-foreground))',
                }}
              >
                {renderEntry(entry)}
              </li>
            ))}

            {/* ✅ Added Inspired By line with translation + KanaDojo link */}
            <li
              className="mb-0 text-[1rem] text-[hsl(var(--muted-foreground))]"
              dir={isRTL ? 'rtl' : 'ltr'}
              style={{
                textAlign: 'center',
                color: 'hsl(var(--muted-foreground))',
              }}
            >
              <span className="text-[hsl(var(--muted-foreground))]">
                {t('inspiredBy')}
              </span>
              <a
                href="https://kanadojo.com/"
                target="_blank"
                rel="noopener noreferrer"
                className="text-[hsl(var(--foreground)/0.9)] hover:text-[hsl(var(--primary))] hover:underline transition-colors"
              >
                KanaDojo かな道場
              </a>
            </li>
          </ul>
        </div>
      </div>
    </section>
  );
}
